version: '3'
services:
        web:
                image: schedulingbackend
                build: .
                ports:
                        - "8886:8886"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
